/**
 * Bake Shiki tokens for marketing-tour diffs.
 * Run after changing site/src/lib/tourData.ts hunk fixtures:
 *   bun run bake:tokens
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { highlightLines } from "../../src/diff/syntaxHighlight";
import { languageFromPath } from "../../src/diff/syntaxLang";
import { fileDiffFor, PR2_FILES, REVIEW_FILES } from "../src/lib/tourData";

export type BakedToken = {
  content: string;
  color?: string;
  fontStyle?: number;
};

const outPath = fileURLToPath(new URL("../src/lib/tourTokens.generated.ts", import.meta.url));

const paths = [...new Set([...REVIEW_FILES, ...PR2_FILES].map((file) => file.path))];

/** lang → line text → tokens */
const byLang = new Map<string, Map<string, BakedToken[]>>();

for (const path of paths) {
  const lang = languageFromPath(path);
  if (!lang) continue;
  const texts = new Set<string>();
  for (const hunk of fileDiffFor(path).hunks) {
    for (const line of hunk.lines) {
      if (line.text) texts.add(line.text);
    }
  }
  if (texts.size === 0) continue;

  const ordered = [...texts];
  const rows = await highlightLines(ordered, lang);
  if (!rows) {
    console.log(`skip ${path} (${lang}): not highlightable`);
    continue;
  }

  let bucket = byLang.get(lang);
  if (!bucket) {
    bucket = new Map();
    byLang.set(lang, bucket);
  }
  ordered.forEach((text, index) => {
    const tokens = (rows[index] ?? []).map((token) => {
      const baked: BakedToken = { content: token.content };
      if (token.color) baked.color = token.color;
      if (token.fontStyle) baked.fontStyle = token.fontStyle;
      return baked;
    });
    bucket!.set(text, tokens);
  });
  console.log(`baked ${path} → ${lang} (${ordered.length} lines)`);
}

const nested: Record<string, Record<string, BakedToken[]>> = {};
for (const [lang, lines] of [...byLang.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  nested[lang] = Object.fromEntries([...lines.entries()].sort(([a], [b]) => a.localeCompare(b)));
}

const body = `/* Generated by site/scripts/bake-tour-tokens.ts — do not edit. */
export type BakedToken = {
  content: string;
  color?: string;
  fontStyle?: number;
};

export const TOUR_TOKENS: Record<string, Record<string, BakedToken[]>> = ${JSON.stringify(nested)};

export function bakedLineTokens(lang: string | null, text: string): BakedToken[] | undefined {
  if (!lang || !text) return undefined;
  return TOUR_TOKENS[lang]?.[text];
}
`;

writeFileSync(outPath, body, "utf8");
console.log(`wrote ${outPath}`);
