import type { IconType } from "react-icons";
import {
  VscFile,
  VscFileBinary,
  VscFileCode,
  VscFileMedia,
  VscFilePdf,
  VscFileText,
  VscFileZip,
} from "react-icons/vsc";
import {
  SiAstro,
  SiBun,
  SiC,
  SiCmake,
  SiClojure,
  SiCoffeescript,
  SiCplusplus,
  SiCss,
  SiDart,
  SiDeno,
  SiDocker,
  SiDotenv,
  SiEditorconfig,
  SiElixir,
  SiElm,
  SiErlang,
  SiEslint,
  SiFishshell,
  SiFortran,
  SiFsharp,
  SiGit,
  SiGnubash,
  SiGnuemacs,
  SiGo,
  SiGraphql,
  SiHaskell,
  SiHtml5,
  SiJavascript,
  SiJinja,
  SiJson,
  SiKotlin,
  SiLatex,
  SiLess,
  SiLua,
  SiMake,
  SiMarkdown,
  SiMdx,
  SiNextdotjs,
  SiNim,
  SiNixos,
  SiNpm,
  SiOcaml,
  SiOpenjdk,
  SiOpengl,
  SiPerl,
  SiPhp,
  SiPnpm,
  SiPrettier,
  SiPrisma,
  SiPug,
  SiPython,
  SiR,
  SiRacket,
  SiReact,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiSharp,
  SiSolidity,
  SiSqlite,
  SiStylus,
  SiSvelte,
  SiSvg,
  SiSwift,
  SiTailwindcss,
  SiTerraform,
  SiToml,
  SiTypescript,
  SiVim,
  SiVite,
  SiVuedotjs,
  SiWebassembly,
  SiXml,
  SiYaml,
  SiYarn,
  SiZig,
  SiZsh,
} from "react-icons/si";
import { cn } from "../lib/cn";
import { fileKindFromPath } from "../lib/fileKind";

interface Spec {
  Icon: IconType;
  color: string;
  label: string;
}

const FILE: Spec = { Icon: VscFile, color: "#E8B86D", label: "File" };

const ICONS: Record<string, Spec> = {
  react: { Icon: SiReact, color: "#61DAFB", label: "React" },
  typescript: { Icon: SiTypescript, color: "#3178C6", label: "TypeScript" },
  javascript: { Icon: SiJavascript, color: "#F7DF1E", label: "JavaScript" },
  rust: { Icon: SiRust, color: "#DEA584", label: "Rust" },
  markdown: { Icon: SiMarkdown, color: "#E8B86D", label: "Markdown" },
  mdx: { Icon: SiMdx, color: "#F9AC00", label: "MDX" },
  css: { Icon: SiCss, color: "#663399", label: "CSS" },
  sass: { Icon: SiSass, color: "#CC6699", label: "Sass" },
  less: { Icon: SiLess, color: "#1D365D", label: "Less" },
  stylus: { Icon: SiStylus, color: "#B3B3B3", label: "Stylus" },
  html: { Icon: SiHtml5, color: "#E34F26", label: "HTML" },
  svg: { Icon: SiSvg, color: "#FFB13B", label: "SVG" },
  python: { Icon: SiPython, color: "#3776AB", label: "Python" },
  go: { Icon: SiGo, color: "#00ADD8", label: "Go" },
  json: { Icon: SiJson, color: "#CBCB41", label: "JSON" },
  yaml: { Icon: SiYaml, color: "#CB171E", label: "YAML" },
  toml: { Icon: SiToml, color: "#9C4121", label: "TOML" },
  xml: { Icon: SiXml, color: "#005FAD", label: "XML" },
  shell: { Icon: SiGnubash, color: "#4EAA25", label: "Shell" },
  zsh: { Icon: SiZsh, color: "#F15A24", label: "Zsh" },
  fish: { Icon: SiFishshell, color: "#4B8BBE", label: "Fish" },
  powershell: { Icon: VscFileCode, color: "#5391FE", label: "PowerShell" },
  docker: { Icon: SiDocker, color: "#2496ED", label: "Docker" },
  git: { Icon: SiGit, color: "#F05032", label: "Git" },
  vue: { Icon: SiVuedotjs, color: "#4FC08D", label: "Vue" },
  svelte: { Icon: SiSvelte, color: "#FF3E00", label: "Svelte" },
  php: { Icon: SiPhp, color: "#777BB4", label: "PHP" },
  ruby: { Icon: SiRuby, color: "#CC342D", label: "Ruby" },
  cpp: { Icon: SiCplusplus, color: "#00599C", label: "C++" },
  c: { Icon: SiC, color: "#A8B9CC", label: "C" },
  csharp: { Icon: SiSharp, color: "#512BD4", label: "C#" },
  kotlin: { Icon: SiKotlin, color: "#7F52FF", label: "Kotlin" },
  swift: { Icon: SiSwift, color: "#F05138", label: "Swift" },
  dart: { Icon: SiDart, color: "#0175C2", label: "Dart" },
  lua: { Icon: SiLua, color: "#2C2D72", label: "Lua" },
  graphql: { Icon: SiGraphql, color: "#E10098", label: "GraphQL" },
  prisma: { Icon: SiPrisma, color: "#5A67D8", label: "Prisma" },
  astro: { Icon: SiAstro, color: "#FF5D01", label: "Astro" },
  zig: { Icon: SiZig, color: "#F7A41D", label: "Zig" },
  elixir: { Icon: SiElixir, color: "#9B72C2", label: "Elixir" },
  haskell: { Icon: SiHaskell, color: "#5D4F85", label: "Haskell" },
  scala: { Icon: SiScala, color: "#DC322F", label: "Scala" },
  clojure: { Icon: SiClojure, color: "#5881D8", label: "Clojure" },
  nim: { Icon: SiNim, color: "#FFE953", label: "Nim" },
  fsharp: { Icon: SiFsharp, color: "#378BBA", label: "F#" },
  solidity: { Icon: SiSolidity, color: "#A9A9A9", label: "Solidity" },
  terraform: { Icon: SiTerraform, color: "#844FBA", label: "Terraform" },
  nix: { Icon: SiNixos, color: "#5277C3", label: "Nix" },
  vim: { Icon: SiVim, color: "#019733", label: "Vim" },
  cmake: { Icon: SiCmake, color: "#064F8C", label: "CMake" },
  make: { Icon: SiMake, color: "#E8B86D", label: "Make" },
  dotenv: { Icon: SiDotenv, color: "#ECD53F", label: "Dotenv" },
  vite: { Icon: SiVite, color: "#646CFF", label: "Vite" },
  tailwind: { Icon: SiTailwindcss, color: "#06B6D4", label: "Tailwind CSS" },
  java: { Icon: SiOpenjdk, color: "#ED8B00", label: "Java" },
  sql: { Icon: SiSqlite, color: "#0F80CC", label: "SQL" },
  coffee: { Icon: SiCoffeescript, color: "#C4A484", label: "CoffeeScript" },
  perl: { Icon: SiPerl, color: "#0073A1", label: "Perl" },
  latex: { Icon: SiLatex, color: "#008080", label: "LaTeX" },
  wasm: { Icon: SiWebassembly, color: "#654FF0", label: "WebAssembly" },
  editorconfig: { Icon: SiEditorconfig, color: "#F5E6C8", label: "EditorConfig" },
  npm: { Icon: SiNpm, color: "#CB3837", label: "npm" },
  bun: { Icon: SiBun, color: "#FBF0DF", label: "Bun" },
  pnpm: { Icon: SiPnpm, color: "#F69220", label: "pnpm" },
  yarn: { Icon: SiYarn, color: "#2C8EBB", label: "Yarn" },
  eslint: { Icon: SiEslint, color: "#4B32C3", label: "ESLint" },
  prettier: { Icon: SiPrettier, color: "#F7B93E", label: "Prettier" },
  next: { Icon: SiNextdotjs, color: "#F5E6C8", label: "Next.js" },
  r: { Icon: SiR, color: "#276DC3", label: "R" },
  pug: { Icon: SiPug, color: "#A86454", label: "Pug" },
  elm: { Icon: SiElm, color: "#1293D8", label: "Elm" },
  erlang: { Icon: SiErlang, color: "#A90533", label: "Erlang" },
  ocaml: { Icon: SiOcaml, color: "#EC6813", label: "OCaml" },
  racket: { Icon: SiRacket, color: "#9F1D20", label: "Racket" },
  emacs: { Icon: SiGnuemacs, color: "#7F5AB6", label: "Emacs" },
  fortran: { Icon: SiFortran, color: "#734F96", label: "Fortran" },
  jinja: { Icon: SiJinja, color: "#B41717", label: "Jinja" },
  glsl: { Icon: SiOpengl, color: "#5586A4", label: "GLSL" },
  deno: { Icon: SiDeno, color: "#F5E6C8", label: "Deno" },
  groovy: { Icon: VscFileCode, color: "#4298B8", label: "Groovy" },
  proto: { Icon: VscFileCode, color: "#E8B86D", label: "Protobuf" },
  objc: { Icon: SiC, color: "#A8B9CC", label: "Objective-C" },
  objcpp: { Icon: SiCplusplus, color: "#00599C", label: "Objective-C++" },
  haml: { Icon: VscFileCode, color: "#EEC2A0", label: "Haml" },
  erb: { Icon: SiRuby, color: "#CC342D", label: "ERB" },
  diff: { Icon: VscFileCode, color: "#E8B86D", label: "Diff" },
  ini: { Icon: VscFileText, color: "#D1D1E0", label: "INI" },
  image: { Icon: VscFileMedia, color: "#E8B86D", label: "Image" },
  pdf: { Icon: VscFilePdf, color: "#E85D04", label: "PDF" },
  archive: { Icon: VscFileZip, color: "#E8B86D", label: "Archive" },
  text: { Icon: VscFileText, color: "#F5E6C8", label: "Text" },
  binary: { Icon: VscFileBinary, color: "#C4B5A0", label: "Binary" },
  file: FILE,
};

export function FileKindIcon({
  path,
  className,
  color,
}: {
  path: string;
  className?: string;
  color?: string;
}) {
  const spec = ICONS[fileKindFromPath(path)] ?? FILE;
  const Icon = spec.Icon;
  return (
    <Icon
      className={cn("shrink-0", className)}
      size={14}
      color={color ?? spec.color}
      title={spec.label}
      aria-hidden
    />
  );
}
